config/routes.rb
Rails.application.routes.draw do
  resources :user_locations
  resources :patient_locations
  get 'sessions/new'

  resources :locations, :tanks, :users, :visits, :patients
  get 'welcome/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  post 'users' => 'users#create'

  

  root 'welcome#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :visits
  has_many :users, through: :visits
  has_one :patient_location
end

app/models/patient_location.rb
class PatientLocation < ActiveRecord::Base
  geocoded_by :address   
  after_validation :geocode

  belongs_to :patient 
  has_many :tanks
end

app/models/tank.rb
class Tank < ActiveRecord::Base
  belongs_to :patient_location
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_one :user_location
  has_many :visits
  has_many :patients, through: :visits
  
end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address   
  after_validation :geocode 
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/patient_locations_controller.rb
class PatientLocationsController < ApplicationController
  before_action :set_patient_location, only: [:show, :edit, :update, :destroy]

  # GET /patient_locations
  # GET /patient_locations.json
  def index
    @patient_locations = PatientLocation.all
  end

  # GET /patient_locations/1
  # GET /patient_locations/1.json
  def show
  end

  # GET /patient_locations/new
  def new
    @patient_location = PatientLocation.new
  end

  # GET /patient_locations/1/edit
  def edit
  end

  # POST /patient_locations
  # POST /patient_locations.json
  def create
    @patient_location = PatientLocation.new(patient_location_params)

    respond_to do |format|
      if @patient_location.save
        format.html { redirect_to @patient_location, notice: 'Patient location was successfully created.' }
        format.json { render :show, status: :created, location: @patient_location }
      else
        format.html { render :new }
        format.json { render json: @patient_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_locations/1
  # PATCH/PUT /patient_locations/1.json
  def update
    respond_to do |format|
      if @patient_location.update(patient_location_params)
        format.html { redirect_to @patient_location, notice: 'Patient location was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient_location }
      else
        format.html { render :edit }
        format.json { render json: @patient_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_locations/1
  # DELETE /patient_locations/1.json
  def destroy
    @patient_location.destroy
    respond_to do |format|
      format.html { redirect_to patient_locations_url, notice: 'Patient location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient_location
      @patient_location = PatientLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_location_params
      params.require(:patient_location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
  end

  def update 
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def new
  end

  def create
    user = User.find_by_username(params[:username])
    # binding.pry
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/tanks_controller.rb
class TanksController < ApplicationController

  before_filter :authorize

  def index
    puts "tanks.index"
    @tanks = Tank.all
  end

  def new
    puts "tanks_controller.create_tank"
    @tank = Tank.new
  end

    def create 
    @tank = Tank.new(tank_params) 
    if @tank.save 
      redirect_to '/tanks' 
    else 
      render 'new' 
    end 
  end
  
  private 
  def tank_params 
    params.require(:tank).permit(:serial_number) 
  end
  
  def update 
  end

  def destroy
    puts "tanks_controller.delete_tank"
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize
  def new
  end

  def update 
  end

  def destroy
  end

  def index
    @users = User.all
  end

 def create
    user = User.new(user_params)
    if user.save
      # session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end


end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def new
    puts "tanks_controller.create_tank"
    @visit = Visit.new
  end

  def create
  end

  def update 
  end

  def destroy
    puts "tanks_controller.delete_tank"
  end

  def index
    puts "tanks.index"
    @visits = Visit.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authorize
  
  def index
    @patients= Patient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patient_locations_helper.rb
module PatientLocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/patient_locations/_form.html.erb
<%= form_for(@patient_location) do |f| %>
  <% if @patient_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient_location.errors.count, "error") %> prohibited this patient_location from being saved:</h2>

      <ul>
      <% @patient_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patient_locations/edit.html.erb
<h1>Editing Patient Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient_location %> |
<%= link_to 'Back', patient_locations_path %>

app/views/patient_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patient Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient_locations.each do |patient_location| %>
      <tr>
        <td><%= patient_location.address %></td>
        <td><%= patient_location.latitude %></td>
        <td><%= patient_location.longitude %></td>
        <td><%= link_to 'Show', patient_location %></td>
        <td><%= link_to 'Edit', edit_patient_location_path(patient_location) %></td>
        <td><%= link_to 'Destroy', patient_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient location', new_patient_location_path %>

app/views/patient_locations/new.html.erb
<h1>New Patient Location</h1>

<%= render 'form' %>

<%= link_to 'Back', patient_locations_path %>

app/views/patient_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @patient_location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @patient_location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @patient_location.longitude %>
</p>

<%= link_to 'Edit', edit_patient_location_path(@patient_location) %> |
<%= link_to 'Back', patient_locations_path %>