config/routes.rb
Rails.application.routes.draw do
  resources :user_locations
  resources :patient_locations
  get 'sessions/new'

  resources :locations, :tanks, :users, :visits, :patients
  get 'welcome/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  post 'users' => 'users#create'

  

  root 'welcome#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :visits
  has_many :users, through: :visits
  has_one :patient_location
end

app/models/patient_location.rb
class PatientLocation < ActiveRecord::Base
  geocoded_by :address   
  after_validation :geocode

  belongs_to :patient 
  has_many :tanks
end

app/models/tank.rb
class Tank < ActiveRecord::Base
  belongs_to :patient_location
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_one :user_location
  has_many :visits
  has_many :patients, through: :visits
  
end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address   
  after_validation :geocode 
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
  end

  def update 
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def new
  end

  def create
    user = User.find_by_username(params[:username])
    # binding.pry
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/tanks_controller.rb
class TanksController < ApplicationController

  before_filter :authorize

  def index
    puts "tanks.index"
    @tanks = Tank.all
  end

  def new
    puts "tanks_controller.create_tank"
    @tank = Tank.new
  end

    def create 
    @tank = Tank.new(tank_params) 
    if @tank.save 
      redirect_to '/tanks' 
    else 
      render 'new' 
    end 
  end
  
  private 
  def tank_params 
    params.require(:tank).permit(:serial_number) 
  end
  
  def update 
  end

  def destroy
    puts "tanks_controller.delete_tank"
  end



end

app/controllers/user_locations_controller.rb
class UserLocationsController < ApplicationController
  before_action :set_user_location, only: [:show, :edit, :update, :destroy]

  # GET /user_locations
  # GET /user_locations.json
  def index
    @user_locations = UserLocation.all
  end

  # GET /user_locations/1
  # GET /user_locations/1.json
  def show
  end

  # GET /user_locations/new
  def new
    @user_location = UserLocation.new
  end

  # GET /user_locations/1/edit
  def edit
  end

  # POST /user_locations
  # POST /user_locations.json
  def create
    @user_location = UserLocation.new(user_location_params)

    respond_to do |format|
      if @user_location.save
        format.html { redirect_to @user_location, notice: 'User location was successfully created.' }
        format.json { render :show, status: :created, location: @user_location }
      else
        format.html { render :new }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_locations/1
  # PATCH/PUT /user_locations/1.json
  def update
    respond_to do |format|
      if @user_location.update(user_location_params)
        format.html { redirect_to @user_location, notice: 'User location was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_location }
      else
        format.html { render :edit }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_locations/1
  # DELETE /user_locations/1.json
  def destroy
    @user_location.destroy
    respond_to do |format|
      format.html { redirect_to user_locations_url, notice: 'User location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_location
      @user_location = UserLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_location_params
      params.require(:user_location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize
  def new
  end

  def update 
  end

  def destroy
  end

  def index
    @users = User.all
  end

 def create
    user = User.new(user_params)
    if user.save
      # session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end


end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def new
    puts "tanks_controller.create_tank"
    @visit = Visit.new
  end

  def create
  end

  def update 
  end

  def destroy
    puts "tanks_controller.delete_tank"
  end

  def index
    puts "tanks.index"
    @visits = Visit.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authorize
  
  def index
    @patients= Patient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patient_locations_helper.rb
module PatientLocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/patients/index.html.erb
<h1>Patients</h1>

<div class="tanks">
  <div class="container">
  
    <% @patients.each do |patient| %> 
      <div class="patient"> 
        <p class="id"><%= patient.id %></p> 
        <p class="first_name"><%= patient.first_name %></p> 
        <p class="last_name"><%= patient.last_name %></p> 
        <p class="tanks_used"><%= patient.tanks_used %></p> 
        <p class="created_at"><%= patient.created_at %></p> 
        <p class="updated_at"><%= patient.updated_at %></p> 
      </div> 
    <% end %>

  </div>
</div>

app/views/tanks/index.html.erb
<h1>Tanks</h1>

<div class="tanks">
  <div class="container">
  
    <% @tanks.each do |tank| %> 
      <div class="tank"> 
        <p class="id"><%= tank.id %></p> 
        <p class="created_at"><%= tank.created_at %></p> 
      </div> 
    <% end %>

  </div>
</div>

app/views/tanks/new.html.erb
<h1>New Tank</h1>

  <%= form_for(@tank) do |f| %>  
      <%= f.label :capacity %><br> 
      <%= f.text_area :serial_number %> 
      <%= f.submit "Create" %> 

  <% end %>

app/views/user_locations/_form.html.erb
<%= form_for(@user_location) do |f| %>
  <% if @user_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_location.errors.count, "error") %> prohibited this user_location from being saved:</h2>

      <ul>
      <% @user_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_locations/edit.html.erb
<h1>Editing User Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_location %> |
<%= link_to 'Back', user_locations_path %>

app/views/user_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_locations.each do |user_location| %>
      <tr>
        <td><%= user_location.address %></td>
        <td><%= user_location.latitude %></td>
        <td><%= user_location.longitude %></td>
        <td><%= link_to 'Show', user_location %></td>
        <td><%= link_to 'Edit', edit_user_location_path(user_location) %></td>
        <td><%= link_to 'Destroy', user_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User location', new_user_location_path %>

app/views/user_locations/new.html.erb
<h1>New User Location</h1>

<%= render 'form' %>

<%= link_to 'Back', user_locations_path %>

app/views/user_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @user_location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @user_location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @user_location.longitude %>
</p>

<%= link_to 'Edit', edit_user_location_path(@user_location) %> |
<%= link_to 'Back', user_locations_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<div class="users">
  <div class="container">
  
    <% @users.each do |user| %> 
      <div class="patient"> 
        <p class="id"><%= user.id %></p> 
        <p class="username"><%= user.username %></p> 
        <p class="first_name"><%= user.first_name %></p> 
        <p class="last_name"><%= user.last_name %></p> 
        <p class="phone_number"><%= user.phone_number %></p> 
        <p class="visit_id"><%= user.visit_id %></p> 
        <p class="created_at"><%= user.created_at %></p> 
        <p class="updated_at"><%= user.updated_at %></p> 
      </div> 
    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<h1>Add New User</h1>

<%= form_for :user, url: '/users' do |f| %>

  Username: <%= f.text_field :username %>
  Password: <%= f.password_field :password %>
  <%= f.submit "Submit" %>

<% end %>

app/views/visits/index.html.erb
<h1>Visits</h1>

<div class="users">
  <div class="container">
  
    <% @visits.each do |visit| %> 
      <div class="patient"> 
        <p class="id"><%= visit.id %></p> 
        <p class="note"><%= visit.note %></p> 
        <p class="patient_id"><%= visit.patient_id %></p> 
        <p class="user_id"><%= visit.user_id %></p> 
        <p class="created_at"><%= visit.created_at %></p> 
        <p class="updated_at"><%= visit.updated_at %></p> 
      </div> 
    <% end %>

  </div>
</div>